# Generated by Django 6.1.1 on 2026-09-07 16:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'A user with that email address already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='name')),
                ('phone', models.CharField(blank=True, help_text='Optional contact number. Format is not enforced here.', max_length=32, verbose_name='phone')),
                ('role', models.CharField(choices=[('user', 'Customer'), ('admin', 'Administrator')], default='user', max_length=10, verbose_name='role')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the user has verified their email via OTP.', verbose_name='verified')),
                ('phone_verified', models.BooleanField(default=False, help_text='Whether the user has verified their phone number.', verbose_name='phone verified')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='accounts_user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='accounts_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='code')),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('login', 'Login')], db_index=True, max_length=12, verbose_name='purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='used')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of incorrect verification attempts.', verbose_name='wrong attempts')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='consumed at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='accounts.user')),
            ],
            options={
                'verbose_name': 'one-time password',
                'verbose_name_plural': 'one-time passwords',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'is_used', 'expires_at'], name='accounts_otp_active_idx')],
            },
        ),
    ]
