import { useMemo, useRef } from "react";
import { cx } from "@/lib/utils";

/**
 * Six separate OTP boxes with:
 *  • auto-focus on mount / focus advances automatically
 *  • backspace navigation (clear then move back)
 *  • arrow-key navigation
 *  • paste support (a complete code pastes into the boxes)
 *  • six-digit validation before onComplete fires
 * OTPs are only ever *entered* here — they are generated by Django.
 */
export default function OTPInput({
  length = 6,
  value = "",
  onChange,
  onComplete,
  disabled = false,
  error = false,
  autoFocus = true,
  label = "One-time password",
}) {
  const refs = useRef([]);
  const digits = useMemo(() => Array.from({ length }).map((_, i) => value[i] || ""), [value, length]);

  const moveFocus = (index) => {
    const next = refs.current[index];
    if (next) {
      next.focus();
      next.select?.();
    }
  };

  const commit = (nextDigits) => {
    const otp = nextDigits.join("");
    onChange?.(otp);
    if (otp.length === length && /^\d{6}$/.test(otp)) onComplete?.(otp);
  };

  const handleChange = (i, e) => {
    const raw = e.target.value.replace(/\D/g, "");
    if (!raw) {
      commit(digits.map((d, j) => (j === i ? "" : d)));
      return;
    }
    // handles a single character OR pasted digits typed into one box
    const next = digits.slice();
    raw.split("").forEach((ch, offset) => {
      const pos = i + offset;
      if (pos < length) next[pos] = ch;
    });
    commit(next);
    const focusTarget = Math.min(i + raw.length, length - 1);
    if (raw.length > 1) moveFocus(focusTarget);
    else if (i + 1 < length) moveFocus(i + 1);
  };

  const handleKeyDown = (i, e) => {
    if (e.key === "Backspace") {
      if (!digits[i] && i > 0) {
        e.preventDefault();
        commit(digits.map((d, j) => (j === i - 1 ? "" : d)));
        moveFocus(i - 1);
      }
    } else if (e.key === "ArrowLeft") {
      e.preventDefault();
      moveFocus(Math.max(0, i - 1));
    } else if (e.key === "ArrowRight") {
      e.preventDefault();
      moveFocus(Math.min(length - 1, i + 1));
    }
  };

  return (
    <div role="group" aria-label={label}>
      <div className="otp-wrap">
        {digits.map((d, i) => (
          <input
            key={i}
            ref={(el) => (refs.current[i] = el)}
            className={cx(
              "otp-box",
              d && "otp-box--filled",
              error && !d && "otp-box--error",
              error && "otp-box--error"
            )}
            value={d}
            inputMode="numeric"
            autoComplete={i === 0 ? "one-time-code" : "off"}
            maxLength={i === 0 ? length : 1}
            disabled={disabled}
            aria-label={`Digit ${i + 1} of ${length}`}
            onChange={(e) => handleChange(i, e)}
            onKeyDown={(e) => handleKeyDown(i, e)}
            onFocus={(e) => e.target.select()}
            autoFocus={autoFocus && i === 0}
          />
        ))}
      </div>
    </div>
  );
}
